### ISSUE TITLE
Add instructions on choosing the right region due to Azure Pass limitations

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/dp-090-databricks-ml#67] opened 2022-04-11 12:06 UTC
# Module: 01
### Task: Create a Cluster

Description of issue
Some regions have very few VMs available for Azure Pass users. For example: West Europe supports Databricks but the last month none of my students has been able to use Databricks in that region due to limitations on the available VMs for their Azure Pass. To be specific: they can make a databricks workspace, but they cannot actually use that workspace because they cannot start a cluster.

The first lab does point to a website where one can find out availability of Databricks in azure regions. However, this site does not inform on the availability of the right VMs for your subscription. 

I realise that I'm asking a difficult question here because I don't know an easy way to find out which VMs you have access to on your Azure Pass subscription, by region. You can figure it out through powershell or similar options, but that's not user friendly for students.

Repro steps:
1. Get an Azure Pass
2. Create a Databricks Workspace in region (for example: West Europe)
3. Try to create a cluster with the default VM size (DS3 v2 or something)

**Comment by madiepev** [comment] 2022-04-11 14:05
@douwevandenberg I understand the frustration but unfortunately this is not a bug/issue in the lab instructions so I'll close the issue. My advice is to recommend students to only choose regions for which you know there is high availability. If you feel this is feedback on the product, you can submit an issue through the Azure portal. If in the future you do think there's a good alternative/tip to add, you can raise a new issue.

**Closed by madiepev** 2022-04-11 14:05 UTC
