### ISSUE TITLE
Lab 4a -4b Issue

### ISSUE THREAD

**Issue by dabrock51** [MicrosoftLearning/dp-090-databricks-ml#59] opened 2021-11-04 01:04 UTC
# Module: 4
### Task: Notebook Cmd 3 and Cmd 8

When loading common libraries the following error is received:

Failure while loading azureml_run_type_providers. Failed to load entrypoint automl = azureml.train.automl.run:AutoMLRun._from_run_dto with exception (cryptography 3.1.1 (/databricks/python3/lib/python3.8/site-packages), Requirement.parse('cryptography>=3.3.1; extra == "crypto"'), {'PyJWT'}).

In attempting to get an instance of the workspace as follows:

ws = Workspace(subscription_id, resource_group, workspace_name)
print(ws)
print('Workspace region:', ws.location)
print('Workspace configuration succeeded')

The following error is received:

get_workspace error using subscription_id=XXXXXXXX-XXXXX-XXXXX-XXXXXXXXXXXX, resource_group_name=XXXXXXXXXX, workspace_name=XXXXXXXXX
ProjectSystemException: ProjectSystemException:---------------------------------------------------------------------------
ErrorResponseWrapperException             Traceback (most recent call last)
/databricks/python/lib/python3.8/site-packages/azureml/_project/_commands.py in get_workspace(auth, subscription_id, resource_group_name, workspace_name, location, cloud, workspace_id)
    435      subscription_id).workspaces
--> 436         return WorkspacesOperations.get(
    437            workspaces,

/databricks/python/lib/python3.8/site-packages/azureml/_base_sdk_common/workspace/operations/workspaces_operations.py in get(self, resource_group_name, workspace_name, custom_headers, raw, is_dataplane, **operation_config)
    109         if response.status_code not in [200]:
--> 110             raise models.ErrorResponseWrapperException(
    111                 self._deserialize, response)

ErrorResponseWrapperException: Operation returned an invalid status code 'Not Found'

The subscription-id, resourcegroup and workspacename variable are correct and the page was properly authenticated.

**Comment by madiepev** [comment] 2021-11-04 14:26
@dabrock51 I could not reproduce your error. Since Cmd 3 already results in an error, it could be an issue with the compute and installed libraries. Does your compute have a ML Databricks Runtime and did you install the three libraries as listed in Cmd 1? I'd also recommend removing your subscription ID, resource group and workspace name from your initial comment to avoid misuse by someone else.

**Comment by dabrock51** [comment] 2021-11-04 15:18
Reply below…

**Comment by madiepev** [comment] 2021-11-04 16:30
@dabrock51 Could you send screenshots of when you get the first error and the libraries installed on your compute?
Also just to check: you're running the notebooks as is? You didn't change anything in the code?

**Comment by dabrock51** [comment] 2021-11-04 19:39
I noticed that I was using the Databricks workspace, not a ML workspace. When I corrected that instruction, the lab worked properly. Sorry for the trouble. 

 

The error when loading the libraries is still there but it does not affect the lab results.

 

Attached is a screen shot.

 

Dave Brockelsby

dbcTraining

712.310.4408

**Comment by madiepev** [comment] 2021-11-04 21:19
Ok! Closing this issue for now. Couldn´t see the screen shot but if it works, it works!

**Closed** 2021-11-04 21:18 UTC
